import 'package:opnwndw/models/project.dart' show Project;
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../shared/widgets/phone_input_field.dart';
import 'package:flutter/services.dart';
import 'project_detail_page.dart';
import 'projects_list_page.dart';
import '../../presentation/providers/project_provider.dart';

class ProjectFormPage extends ConsumerStatefulWidget {
  const ProjectFormPage({super.key});

  @override
  ConsumerState<ProjectFormPage> createState() => _ProjectFormPageState();
}

class UpperCaseTextFormatter extends TextInputFormatter {
  @override
  TextEditingValue formatEditUpdate(
    TextEditingValue oldValue,
    TextEditingValue newValue,
  ) {
    return newValue.copyWith(
      text: newValue.text.toUpperCase(),
      selection: newValue.selection,
    );
  }
}

class CapitalizeEachWordTextFormatter extends TextInputFormatter {
  String _capitalizeEachWord(String text) {
    if (text.isEmpty) return text;
    return text
        .split(' ')
        .map(
          (word) => word.isEmpty
              ? ''
              : '${word[0].toUpperCase()}${word.substring(1).toLowerCase()}',
        )
        .join(' ');
  }

  @override
  TextEditingValue formatEditUpdate(
    TextEditingValue oldValue,
    TextEditingValue newValue,
  ) {
    final newText = _capitalizeEachWord(newValue.text);
    return newValue.copyWith(text: newText, selection: newValue.selection);
  }
}

class _ProjectFormPageState extends ConsumerState<ProjectFormPage> {
  final _formKey = GlobalKey<FormState>();

  final _nameController = TextEditingController();
  final _addressController = TextEditingController();
  final _descriptionController = TextEditingController();

  String _autoGeneratedId = '';
  String _phoneNumber = '';

  @override
  void initState() {
    super.initState();
    _generateAutoId();
  }

  void _generateAutoId() {
    final timestamp = DateTime.now().millisecondsSinceEpoch;
    final random = DateTime.now().microsecondsSinceEpoch % 10000;
    setState(() {
      _autoGeneratedId = 'PROJ_${timestamp}_$random';
    });
  }

  void _saveProject() async {
    if (_formKey.currentState!.validate()) {
      // Telefon numarası kontrolü
      if (_phoneNumber.isEmpty || _phoneNumber.length < 10) {
        // 🚨 EKLENDİ: Uzunluk kontrolü
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: const Text('Lütfen geçerli telefon numarası giriniz'),
            backgroundColor: Colors.red,
            behavior: SnackBarBehavior.floating,
          ),
        );
        return;
      }

      final project = Project(
        id: _autoGeneratedId,
        name: _nameController.text.trim(), // 🚨 EKLENDİ: trim()
        phone: _phoneNumber,
        address: _addressController.text.trim(), // 🚨 EKLENDİ: trim()
        description: _descriptionController.text.trim(), // 🚨 EKLENDİ: trim()
        createdAt: DateTime.now()
            .toIso8601String(), // 🚨 DEĞİŞTİ: toString() -> toIso8601String()
      );

      try {
        // 🚨 DEĞİŞTİ: Önce state'i dinle, sonra kaydet
        final notifier = ref.read(projectProvider.notifier);
        await notifier.addProject(project);

        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text('${project.name} projesi oluşturuldu!'),
              backgroundColor: Colors.green,
              behavior: SnackBarBehavior.floating,
              duration: Duration(seconds: 2),
            ),
          );

          // 🚨 DEĞİŞİKLİK BURADA:
          // 1. Önce Projelerim listesine git (Ana Sayfa'yı koruyarak)
          Navigator.of(context).pushAndRemoveUntil(
            MaterialPageRoute(builder: (context) => const ProjectsListPage()),
            (route) => route
                .isFirst, // Sadece ilk sayfayı (HomePage) tut, formu kaldır
          );

          // 2. Hemen ardından oluşturulan projenin detay sayfasını aç
          Navigator.of(context).push(
            MaterialPageRoute(
              builder: (context) => ProjectDetailPage(project: project),
            ),
          );
        }
      } catch (e) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Hata: $e'), backgroundColor: Colors.red),
        );
      }
    }
  }

  @override
  void dispose() {
    _nameController.dispose();
    _addressController.dispose();
    _descriptionController.dispose();
    super.dispose();
  }

  Widget _buildLeftContent() {
    return Column(
      children: [
        TextFormField(
          controller: _nameController,
          decoration: const InputDecoration(
            labelText: 'Ad Soyad',
            border: OutlineInputBorder(),
            prefixIcon: Icon(Icons.person),
          ),
          inputFormatters: [UpperCaseTextFormatter()],
          style: const TextStyle(fontSize: 16, fontWeight: FontWeight.w500),
          validator: (value) {
            if (value == null || value.isEmpty)
              return 'Lütfen ad soyad giriniz';
            if (value.split(' ').length < 2)
              return 'Lütfen ad ve soyad giriniz';
            return null;
          },
        ),
        const SizedBox(height: 16),
        PhoneInputField(onChanged: (value) => _phoneNumber = value),
        const SizedBox(height: 16),
        TextFormField(
          controller: _addressController,
          maxLines: 3,
          decoration: const InputDecoration(
            labelText: 'Adres',
            border: OutlineInputBorder(),
            prefixIcon: Icon(Icons.location_on),
          ),
          inputFormatters: [CapitalizeEachWordTextFormatter()],
          style: const TextStyle(fontSize: 16, fontWeight: FontWeight.w500),
          validator: (value) {
            if (value == null || value.isEmpty) return 'Lütfen adres giriniz';
            if (value.length < 10) return 'Lütfen daha detaylı adres giriniz';
            return null;
          },
        ),
      ],
    );
  }

  @override
  Widget build(BuildContext context) {
    final isLandscape =
        MediaQuery.of(context).orientation == Orientation.landscape;
    final padding = const EdgeInsets.all(20.0);

    return Scaffold(
      appBar: AppBar(
        title: const Text('Yeni Proje Oluştur'),
        centerTitle: true,
        actions: [
          IconButton(
            icon: const Icon(Icons.save),
            onPressed: _saveProject,
            tooltip: 'Projeyi Kaydet',
          ),
          IconButton(
            icon: const Icon(Icons.close),
            onPressed: () => Navigator.pop(context),
            tooltip: 'İptal',
          ),
        ],
      ),
      body: Form(
        key: _formKey,
        child: Padding(
          padding: padding,
          child: isLandscape
              ? Row(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Expanded(
                      flex: 1,
                      child: SingleChildScrollView(child: _buildLeftContent()),
                    ),
                    const SizedBox(width: 20),
                    Expanded(
                      flex: 1,
                      child: TextFormField(
                        controller: _descriptionController,
                        maxLines: null,
                        expands: true,
                        textAlignVertical: TextAlignVertical.top,
                        decoration: const InputDecoration(
                          labelText: 'Açıklama',
                          border: OutlineInputBorder(),
                          prefixIcon: Icon(Icons.description),
                          contentPadding: EdgeInsets.symmetric(
                            horizontal: 16,
                            vertical: 16,
                          ),
                        ),
                        style: const TextStyle(
                          fontSize: 16,
                          fontWeight: FontWeight.w500,
                        ),
                      ),
                    ),
                  ],
                )
              : SingleChildScrollView(
                  child: Column(
                    children: [
                      _buildLeftContent(),
                      const SizedBox(height: 16),
                      TextFormField(
                        controller: _descriptionController,
                        maxLines: 5,
                        decoration: const InputDecoration(
                          labelText: 'Açıklama',
                          border: OutlineInputBorder(),
                          prefixIcon: Icon(Icons.description),
                          contentPadding: EdgeInsets.symmetric(
                            horizontal: 16,
                            vertical: 16,
                          ),
                        ),
                        style: const TextStyle(
                          fontSize: 16,
                          fontWeight: FontWeight.w500,
                        ),
                      ),
                      const SizedBox(height: 20),
                    ],
                  ),
                ),
        ),
      ),
    );
  }
}
